input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Heart)
    basic.pause(3000)
    basic.showIcon(IconNames.Yes)
    basic.pause(3000)
    basic.showIcon(IconNames.Happy)
    basic.pause(3000)
    basic.clearScreen()
})
input.onButtonPressed(Button.AB, function () {
    basic.showString("Hello!")
    basic.showString("Nice to meet you")
    basic.pause(2000)
    basic.showIcon(IconNames.Asleep)
    basic.showIcon(IconNames.Duck)
    basic.pause(2000)
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function () {
    basic.showNumber(26)
    basic.pause(2000)
    basic.showString("Saxophone")
    basic.pause(2000)
    basic.clearScreen()
})
basic.showString("Wadsamon")
basic.pause(3000)
basic.showString("Thuma")
basic.pause(3000)
basic.showString("M.4/2")
basic.pause(3000)
